language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin

install:
  # Install Composer dependencies.
  - cd $TRAVIS_BUILD_DIR
  - composer require "satooshi/php-coveralls:0.6.*" --no-update
  - composer install --prefer-dist

script:
  # Run PHPUnit tests and submit code coverage statistics.
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c ./phpunit.xml.dist --bootstrap ./vendor/autoload.php --verbose --debug --coverage-clover ./build/logs/clover.xml || exit 1
  - php ./vendor/bin/coveralls -v -c ./.coveralls.yml
