alternative_signs: {  }
ISO4217Code: DEM
minorUnit: 2
ISO4217Number: '276'
sign: Â¤
title: 'German mark'
usage:
    - { ISO8601From: '1948-06-20', ISO8601To: '2002-02-28', ISO3166Code: DE }
    - { ISO8601From: '1999-10-02', ISO8601To: '2002-05-15', ISO3166Code: ME }
