ISO4217Code: EGP
minorUnit: 2
ISO4217Number: '818'
sign: Â¤
title: 'Egyptian Pound'
usage:
    - { ISO8601From: '1885-11-14', ISO8601To: '', ISO3166Code: EG }
    - { ISO8601From: '1920-11-11', ISO8601To: '1931-04-19', ISO3166Code: IQ }
    - { ISO8601From: '1889-01-19', ISO8601To: '1958-01-01', ISO3166Code: SD }
