alternativeSigns: {  }
ISO4217Code: JOD
minorUnit: 3
ISO4217Number: '400'
sign: JD
title: 'Jordanian Dinar'
usage:
    - { ISO8601From: '1950-07-01', ISO8601To: '', ISO3166Code: JO }
    - { ISO8601From: '1996-02-12', ISO8601To: '', ISO3166Code: PS }
    - { ISO8601From: '1950-07-01', ISO8601To: '1967-06-01', ISO3166Code: PS }
