alternative_signs: {  }
ISO4217Code: MAD
minorUnit: 2
ISO4217Number: '504'
sign: Â¤
title: 'Moroccan Dirham'
usage:
    - { ISO8601From: '1976-02-26', ISO8601To: '', ISO3166Code: EH }
    - { ISO8601From: '1959-10-17', ISO8601To: '', ISO3166Code: MA }
