ISO4217Code: MYR
minorUnit: 2
ISO4217Number: '458'
sign: Â¤
title: 'Malaysian Ringgit'
usage:
    - { ISO8601From: '1963-09-16', ISO8601To: '1967-06-12', ISO3166Code: BN }
    - { ISO8601From: '1963-09-16', ISO8601To: '', ISO3166Code: MY }
    - { ISO8601From: '1963-09-16', ISO8601To: '1967-06-12', ISO3166Code: SG }
