alternative_signs: {  }
ISO4217Code: NZD
minorUnit: 2
ISO4217Number: '554'
sign: $
title: 'New Zealand Dollar'
usage:
    - { ISO8601From: '1967-07-10', ISO8601To: '', ISO3166Code: CK }
    - { ISO8601From: '1967-07-10', ISO8601To: '', ISO3166Code: NU }
    - { ISO8601From: '1967-07-10', ISO8601To: '', ISO3166Code: NZ }
    - { ISO8601From: '1969-01-13', ISO8601To: '', ISO3166Code: PN }
    - { ISO8601From: '1967-07-10', ISO8601To: '', ISO3166Code: TK }
