alternative_signs: {  }
ISO4217Code: PKR
minorUnit: 2
ISO4217Number: '586'
sign: â‚¨
title: 'Pakistan Rupee'
usage:
    - { ISO8601From: '1948-04-01', ISO8601To: '1972-01-01', ISO3166Code: BD }
    - { ISO8601From: '1948-04-01', ISO8601To: '', ISO3166Code: PK }
