alternative_signs: {  }
ISO4217Code: PLZ
minorUnit: null
ISO4217Number: '616'
sign: z≈Ç
title: 'Polish zloty A/94'
usage:
    - { ISO8601From: '1950-10-28', ISO8601To: '1994-12-31', ISO3166Code: PL }
