alternativeSigns: {  }
ISO4217Code: PTE
minorUnit: 100
ISO4217Number: '620'
sign: î€Š
title: 'Portuguese escudo'
usage:
    - { ISO8601From: '1911-05-22', ISO8601To: '1975-07-05', ISO3166Code: CV }
    - { ISO8601From: '1911-05-22', ISO8601To: '2002-02-28', ISO3166Code: PT }
