alternative_signs: {  }
ISO4217Code: TPE
minorUnit: null
ISO4217Number: null
sign: Â¤
title: null
usage:
    - { ISO8601From: '1959-01-02', ISO8601To: '2002-05-20', ISO3166Code: TL }
    - { ISO8601From: '1959-01-02', ISO8601To: '2002-05-20', ISO3166Code: TP }
