alternative_signs: {  }
ISO4217Code: UAK
minorUnit: 2
ISO4217Number: '804'
sign: Â¤
title: 'Ukrainian karbovanets'
usage:
    - { ISO8601From: '1992-11-13', ISO8601To: '1993-10-17', ISO3166Code: UA }
