alternative_signs: {  }
ISO4217Code: UYI
minorUnit: 0
ISO4217Number: '940'
sign: Â¤
title: 'Uruguay Peso en Unidades Indexadas (URUIURUI)'
usage:
    - { ISO8601From: '', ISO8601To: '', ISO3166Code: UY }
