alternative_signs: {  }
ISO4217Code: XTS
minorUnit: 0
ISO4217Number: '963'
sign: Â¤
title: 'Codes specifically reserved for testing purposes'
usage:
    - { ISO8601From: '', ISO8601To: '', ISO3166Code: ZZ }
