alternativeSigns: {  }
ISO4217Code: XXX
minorUnit: 0
ISO4217Number: '999'
sign: Â¤
title: 'The codes assigned for transactions where no currency is involved'
usage:
    - { ISO8601From: '', ISO8601To: '', ISO3166Code: AQ }
    - { ISO8601From: '', ISO8601To: '', ISO3166Code: ZZ }
