alternativeSigns: {  }
ISO4217Code: YUN
minorUnit: 2
ISO4217Number: null
sign: дин
title: 'Yugoslav dinar'
usage:
    - { ISO8601From: '1990-01-01', ISO8601To: '1992-07-01', ISO3166Code: BA }
    - { ISO8601From: '1990-01-01', ISO8601To: '1991-12-23', ISO3166Code: HR }
    - { ISO8601From: '1990-01-01', ISO8601To: '1992-07-24', ISO3166Code: YU }
