alternative_signs: {  }
ISO4217Code: ZAL
minorUnit: 0
ISO4217Number: '991'
sign: Â¤
title: 'South African financial rand'
usage:
    - { ISO8601From: 1979-01, ISO8601To: 1983-02, ISO3166Code: ZA }
    - { ISO8601From: '1985-09-01', ISO8601To: '1995-03-13', ISO3166Code: ZA }
