alternativeSigns: {  }
ISO4217Code: ZAR
minorUnit: 2
ISO4217Number: '710'
sign: R
title: Rand
usage:
    - { ISO8601From: '1961-02-14', ISO8601To: '1976-08-23', ISO3166Code: BW }
    - { ISO8601From: '1961-02-14', ISO8601To: '', ISO3166Code: LS }
    - { ISO8601From: '1961-02-14', ISO8601To: '1993-01-01', ISO3166Code: NA }
    - { ISO8601From: '1961-02-14', ISO8601To: '', ISO3166Code: ZA }
