alternative_signs: {  }
ISO4217Code: ZRN
minorUnit: 2
ISO4217Number: '180'
sign: Ƶ
title: 'Zaïrean new zaïre'
usage:
    - { ISO8601From: '1993-11-01', ISO8601To: '1998-07-01', ISO3166Code: CD }
    - { ISO8601From: '1993-11-01', ISO8601To: 1998-07, ISO3166Code: ZR }
